print("Welcome to the Band Name Generator \n")
a =input("What's the name of the city you grew up in? \n")
b=input("What's your pet name? \n")
print(f"Your band name could be {a} {b}")
print("Your band name could be " + a + " " + b)
